services:
  - type: worker
    name: bnb-profit-harvester-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
      - key: TZ
        value: UTC

